# Form implementation generated from reading ui file 'gui/list.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Workspace(object):
    def setupUi(self, Workspace):
        Workspace.setObjectName("Workspace")
        Workspace.resize(354, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Workspace.sizePolicy().hasHeightForWidth())
        Workspace.setSizePolicy(sizePolicy)
        Workspace.setMinimumSize(QtCore.QSize(354, 602))
        Workspace.setMaximumSize(QtCore.QSize(380, 602))
        Workspace.setSizeIncrement(QtCore.QSize(0, 0))
        Workspace.setBaseSize(QtCore.QSize(0, 0))
        Workspace.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Workspace.setWindowIcon(icon)
        Workspace.setStyleSheet("/* Main section */\n"
"\n"
"QWidget {\n"
"    background-color: #FFFFFF;\n"
"    color: #334155;\n"
"}\n"
"\n"
"/* Table Styling */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius:3px;\n"
"    gridline-color: #F1F5F9;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border:none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #E0F2FE;\n"
"    color: #0369A1;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F8FAFC;\n"
"    color: #64748B;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #E2E8F0;\n"
"}\n"
"\n"
"/* Button Styling */\n"
"QPushButton {\n"
"    max-height:15px;\n"
"    padding: 8px;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #475569;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F0F9FF;\n"
"    border-color: #0EA5E9;\n"
"    color: #0EA5E9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E0F2FE;\n"
"    color: #0369A1;\n"
"}\n"
"\n"
"/* Input Fields */\n"
"QLineEdit{\n"
"    max-height:15px;\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #334155;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color: #0EA5E9;\n"
"    background-color: #F0F9FF;\n"
"}\n"
"\n"
"Line{\n"
"    background-color: rgba(40, 180, 244, 15);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Workspace)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_list = QtWidgets.QWidget(parent=Workspace)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        self.widget_list.setFont(font)
        self.widget_list.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.widget_list.setStyleSheet("")
        self.widget_list.setObjectName("widget_list")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_list)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table_Barcodes = QtWidgets.QTableWidget(parent=self.widget_list)
        self.table_Barcodes.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.table_Barcodes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.table_Barcodes.setStyleSheet("")
        self.table_Barcodes.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.table_Barcodes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.table_Barcodes.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_Barcodes.setTabKeyNavigation(False)
        self.table_Barcodes.setProperty("showDropIndicator", False)
        self.table_Barcodes.setDragDropOverwriteMode(False)
        self.table_Barcodes.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.table_Barcodes.setAlternatingRowColors(True)
        self.table_Barcodes.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_Barcodes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_Barcodes.setShowGrid(True)
        self.table_Barcodes.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.table_Barcodes.setRowCount(0)
        self.table_Barcodes.setObjectName("table_Barcodes")
        self.table_Barcodes.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_Barcodes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Barcodes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Barcodes.setHorizontalHeaderItem(2, item)
        self.table_Barcodes.horizontalHeader().setDefaultSectionSize(140)
        self.table_Barcodes.horizontalHeader().setHighlightSections(True)
        self.table_Barcodes.horizontalHeader().setMinimumSectionSize(31)
        self.table_Barcodes.horizontalHeader().setSortIndicatorShown(False)
        self.table_Barcodes.verticalHeader().setVisible(True)
        self.table_Barcodes.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_4.addWidget(self.table_Barcodes)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_close = QtWidgets.QPushButton(parent=self.widget_list)
        self.button_close.setMaximumSize(QtCore.QSize(125, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.button_close.setFont(font)
        self.button_close.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_close.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button_close.setStyleSheet("QPushButton{\n"
"    color:#006EFF;\n"
"}")
        self.button_close.setIconSize(QtCore.QSize(20, 20))
        self.button_close.setCheckable(False)
        self.button_close.setAutoExclusive(False)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_5.addWidget(self.button_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.widget_list)

        self.retranslateUi(Workspace)
        QtCore.QMetaObject.connectSlotsByName(Workspace)

    def retranslateUi(self, Workspace):
        _translate = QtCore.QCoreApplication.translate
        self.table_Barcodes.setSortingEnabled(False)
        item = self.table_Barcodes.horizontalHeaderItem(0)
        item.setText(_translate("Workspace", "ID"))
        item = self.table_Barcodes.horizontalHeaderItem(1)
        item.setText(_translate("Workspace", "Barkod"))
        item = self.table_Barcodes.horizontalHeaderItem(2)
        item.setText(_translate("Workspace", "Miqdar"))
        self.button_close.setText(_translate("Workspace", "Bağla"))

import resources
