# Form implementation generated from reading ui file 'gui/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(905, 630)
        Main.setMaximumSize(QtCore.QSize(905, 630))
        Main.setAcceptDrops(True)
        Main.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Main.setWindowIcon(icon)
        Main.setStyleSheet("/* Main section */\n"
"\n"
"QWidget {\n"
"    background-color: #FFFFFF;\n"
"    color: #334155;\n"
"}\n"
"\n"
"/* Table Styling */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius:3px;\n"
"    gridline-color: #F1F5F9;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border:none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #E0F2FE;\n"
"    color: #0369A1;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F8FAFC;\n"
"    color: #64748B;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #E2E8F0;\n"
"}\n"
"\n"
"/* Button Styling */\n"
"QPushButton {\n"
"    max-height:15px;\n"
"    padding: 8px;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #475569;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F0F9FF;\n"
"    border-color: #0EA5E9;\n"
"    color: #0EA5E9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E0F2FE;\n"
"    color: #0369A1;\n"
"}\n"
"\n"
"/* Input Fields */\n"
"QLineEdit{\n"
"    max-height:15px;\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #334155;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color: #0EA5E9;\n"
"    background-color: #F0F9FF;\n"
"}\n"
"\n"
"Line{\n"
"    background-color: rgba(40, 180, 244, 15);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.top = QtWidgets.QWidget(parent=self.centralwidget)
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_users = QtWidgets.QPushButton(parent=self.top)
        self.btn_users.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_users.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.btn_users.setFont(font)
        self.btn_users.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_users.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_users.setToolTipDuration(-1)
        self.btn_users.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_users.setAutoFillBackground(False)
        self.btn_users.setStyleSheet("")
        self.btn_users.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/icons/stakeholder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_users.setIcon(icon1)
        self.btn_users.setIconSize(QtCore.QSize(20, 20))
        self.btn_users.setCheckable(True)
        self.btn_users.setChecked(False)
        self.btn_users.setAutoExclusive(True)
        self.btn_users.setObjectName("btn_users")
        self.horizontalLayout_2.addWidget(self.btn_users)
        self.btn_barcodes = QtWidgets.QPushButton(parent=self.top)
        self.btn_barcodes.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_barcodes.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.btn_barcodes.setFont(font)
        self.btn_barcodes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_barcodes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_barcodes.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_barcodes.setAutoFillBackground(False)
        self.btn_barcodes.setStyleSheet("")
        self.btn_barcodes.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/assets/icons/verified.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_barcodes.setIcon(icon2)
        self.btn_barcodes.setIconSize(QtCore.QSize(20, 20))
        self.btn_barcodes.setCheckable(True)
        self.btn_barcodes.setChecked(False)
        self.btn_barcodes.setAutoExclusive(True)
        self.btn_barcodes.setObjectName("btn_barcodes")
        self.horizontalLayout_2.addWidget(self.btn_barcodes)
        self.btn_show_info = QtWidgets.QPushButton(parent=self.top)
        self.btn_show_info.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_show_info.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.btn_show_info.setFont(font)
        self.btn_show_info.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_show_info.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_show_info.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_show_info.setAutoFillBackground(False)
        self.btn_show_info.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/assets/icons/info.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_show_info.setIcon(icon3)
        self.btn_show_info.setIconSize(QtCore.QSize(20, 20))
        self.btn_show_info.setCheckable(True)
        self.btn_show_info.setChecked(False)
        self.btn_show_info.setAutoExclusive(True)
        self.btn_show_info.setObjectName("btn_show_info")
        self.horizontalLayout_2.addWidget(self.btn_show_info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.top, 0, 0, 1, 1)
        self.pages = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.pages.setObjectName("pages")
        self.users_page = QtWidgets.QWidget()
        self.users_page.setObjectName("users_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.users_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.users_widget = QtWidgets.QWidget(parent=self.users_page)
        self.users_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.users_widget.setStyleSheet("")
        self.users_widget.setObjectName("users_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.users_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Users = QtWidgets.QLabel(parent=self.users_widget)
        self.label_Users.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_Users.setFont(font)
        self.label_Users.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_Users.setStyleSheet("background-color:transparent;\n"
"padding-top:4px;")
        self.label_Users.setObjectName("label_Users")
        self.horizontalLayout_4.addWidget(self.label_Users)
        spacerItem1 = QtWidgets.QSpacerItem(40, 27, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_new_User = QtWidgets.QPushButton(parent=self.users_widget)
        self.btn_new_User.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_new_User.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        self.btn_new_User.setFont(font)
        self.btn_new_User.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_new_User.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_new_User.setToolTip("")
        self.btn_new_User.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_new_User.setAutoFillBackground(False)
        self.btn_new_User.setStyleSheet("")
        self.btn_new_User.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/assets/icons/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_new_User.setIcon(icon4)
        self.btn_new_User.setIconSize(QtCore.QSize(20, 20))
        self.btn_new_User.setCheckable(True)
        self.btn_new_User.setAutoExclusive(True)
        self.btn_new_User.setObjectName("btn_new_User")
        self.horizontalLayout_4.addWidget(self.btn_new_User)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_21 = QtWidgets.QFrame(parent=self.users_widget)
        self.line_21.setMaximumSize(QtCore.QSize(16777215, 1))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line_21.setFont(font)
        self.line_21.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.line_21.setStyleSheet("")
        self.line_21.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout.addWidget(self.line_21)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.table_Users = QtWidgets.QTableWidget(parent=self.users_widget)
        self.table_Users.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.table_Users.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.table_Users.setStyleSheet("")
        self.table_Users.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.table_Users.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.table_Users.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_Users.setTabKeyNavigation(False)
        self.table_Users.setProperty("showDropIndicator", False)
        self.table_Users.setDragDropOverwriteMode(False)
        self.table_Users.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.table_Users.setAlternatingRowColors(True)
        self.table_Users.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_Users.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_Users.setShowGrid(True)
        self.table_Users.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.table_Users.setRowCount(0)
        self.table_Users.setObjectName("table_Users")
        self.table_Users.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_Users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Users.setHorizontalHeaderItem(2, item)
        self.table_Users.horizontalHeader().setDefaultSectionSize(130)
        self.table_Users.horizontalHeader().setHighlightSections(True)
        self.table_Users.horizontalHeader().setMinimumSectionSize(31)
        self.table_Users.horizontalHeader().setSortIndicatorShown(False)
        self.table_Users.verticalHeader().setVisible(True)
        self.table_Users.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.table_Users)
        self.gridLayout_2.addWidget(self.users_widget, 0, 0, 1, 1)
        self.pages.addWidget(self.users_page)
        self.barcodes_page = QtWidgets.QWidget()
        self.barcodes_page.setObjectName("barcodes_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.barcodes_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Barcodes_widget = QtWidgets.QWidget(parent=self.barcodes_page)
        self.Barcodes_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Barcodes_widget.setStyleSheet("")
        self.Barcodes_widget.setObjectName("Barcodes_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Barcodes_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_Barcodes = QtWidgets.QLabel(parent=self.Barcodes_widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_Barcodes.setFont(font)
        self.label_Barcodes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_Barcodes.setStyleSheet("background-color:transparent;\n"
"padding-top:4px;")
        self.label_Barcodes.setObjectName("label_Barcodes")
        self.horizontalLayout_6.addWidget(self.label_Barcodes)
        spacerItem3 = QtWidgets.QSpacerItem(40, 27, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btn_reload_Barcodes = QtWidgets.QPushButton(parent=self.Barcodes_widget)
        self.btn_reload_Barcodes.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_reload_Barcodes.setFont(font)
        self.btn_reload_Barcodes.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/assets/icons/return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_reload_Barcodes.setIcon(icon5)
        self.btn_reload_Barcodes.setIconSize(QtCore.QSize(20, 20))
        self.btn_reload_Barcodes.setCheckable(True)
        self.btn_reload_Barcodes.setAutoExclusive(True)
        self.btn_reload_Barcodes.setObjectName("btn_reload_Barcodes")
        self.horizontalLayout_6.addWidget(self.btn_reload_Barcodes)
        self.btn_export_choosen = QtWidgets.QPushButton(parent=self.Barcodes_widget)
        self.btn_export_choosen.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/assets/icons/xls.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_export_choosen.setIcon(icon6)
        self.btn_export_choosen.setIconSize(QtCore.QSize(20, 20))
        self.btn_export_choosen.setCheckable(True)
        self.btn_export_choosen.setAutoExclusive(True)
        self.btn_export_choosen.setObjectName("btn_export_choosen")
        self.horizontalLayout_6.addWidget(self.btn_export_choosen)
        self.btn_delete_choosen = QtWidgets.QPushButton(parent=self.Barcodes_widget)
        self.btn_delete_choosen.setMaximumSize(QtCore.QSize(40, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.btn_delete_choosen.setFont(font)
        self.btn_delete_choosen.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_delete_choosen.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btn_delete_choosen.setStyleSheet("")
        self.btn_delete_choosen.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/assets/icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_delete_choosen.setIcon(icon7)
        self.btn_delete_choosen.setIconSize(QtCore.QSize(20, 20))
        self.btn_delete_choosen.setCheckable(False)
        self.btn_delete_choosen.setAutoExclusive(False)
        self.btn_delete_choosen.setObjectName("btn_delete_choosen")
        self.horizontalLayout_6.addWidget(self.btn_delete_choosen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.line_23 = QtWidgets.QFrame(parent=self.Barcodes_widget)
        self.line_23.setMaximumSize(QtCore.QSize(16777215, 1))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line_23.setFont(font)
        self.line_23.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.line_23.setStyleSheet("")
        self.line_23.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_3.addWidget(self.line_23)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.table_Workspaces = QtWidgets.QTableWidget(parent=self.Barcodes_widget)
        self.table_Workspaces.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.table_Workspaces.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.table_Workspaces.setStyleSheet("")
        self.table_Workspaces.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.table_Workspaces.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.table_Workspaces.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_Workspaces.setTabKeyNavigation(False)
        self.table_Workspaces.setProperty("showDropIndicator", False)
        self.table_Workspaces.setDragDropOverwriteMode(False)
        self.table_Workspaces.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.table_Workspaces.setAlternatingRowColors(True)
        self.table_Workspaces.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.table_Workspaces.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_Workspaces.setShowGrid(True)
        self.table_Workspaces.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.table_Workspaces.setRowCount(0)
        self.table_Workspaces.setObjectName("table_Workspaces")
        self.table_Workspaces.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table_Workspaces.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Workspaces.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Workspaces.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Workspaces.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Workspaces.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Workspaces.setHorizontalHeaderItem(5, item)
        self.table_Workspaces.horizontalHeader().setDefaultSectionSize(130)
        self.table_Workspaces.horizontalHeader().setHighlightSections(True)
        self.table_Workspaces.horizontalHeader().setMinimumSectionSize(31)
        self.table_Workspaces.horizontalHeader().setSortIndicatorShown(False)
        self.table_Workspaces.verticalHeader().setVisible(True)
        self.table_Workspaces.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.table_Workspaces)
        self.gridLayout_4.addWidget(self.Barcodes_widget, 0, 0, 1, 1)
        self.pages.addWidget(self.barcodes_page)
        self.gridLayout.addWidget(self.pages, 1, 0, 1, 1)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        self.btn_users.setToolTip(_translate("Main", "İstifadəçilər"))
        self.btn_barcodes.setToolTip(_translate("Main", "Barkodlar"))
        self.btn_show_info.setToolTip(_translate("Main", "Barkodlar"))
        self.label_Users.setText(_translate("Main", "İstifadəçilər"))
        self.table_Users.setSortingEnabled(False)
        item = self.table_Users.horizontalHeaderItem(0)
        item.setText(_translate("Main", "ID"))
        item = self.table_Users.horizontalHeaderItem(1)
        item.setText(_translate("Main", "İstifadəçi"))
        item = self.table_Users.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Şifrə"))
        self.label_Barcodes.setText(_translate("Main", "Barkodlar"))
        self.table_Workspaces.setSortingEnabled(False)
        item = self.table_Workspaces.horizontalHeaderItem(0)
        item.setText(_translate("Main", "ID"))
        item = self.table_Workspaces.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Tarix"))
        item = self.table_Workspaces.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Anbar"))
        item = self.table_Workspaces.horizontalHeaderItem(3)
        item.setText(_translate("Main", "İstifadəçi"))
        item = self.table_Workspaces.horizontalHeaderItem(4)
        item.setText(_translate("Main", "Barkod sayı"))
        item = self.table_Workspaces.horizontalHeaderItem(5)
        item.setText(_translate("Main", "Ümumi miqdar"))

import resources
