# Form implementation generated from reading ui file 'gui/user.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_User(object):
    def setupUi(self, User):
        User.setObjectName("User")
        User.resize(326, 305)
        User.setMinimumSize(QtCore.QSize(0, 0))
        User.setMaximumSize(QtCore.QSize(326, 305))
        User.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        User.setWindowIcon(icon)
        User.setStyleSheet("/* Main section */\n"
"\n"
"QWidget {\n"
"    background-color: #FFFFFF;\n"
"    color: #334155;\n"
"}\n"
"/* Button Styling */\n"
"QPushButton {\n"
"    max-height:15px;\n"
"    padding: 8px;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #475569;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F0F9FF;\n"
"    border-color: #0EA5E9;\n"
"    color: #0EA5E9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E0F2FE;\n"
"    color: #0369A1;\n"
"}\n"
"\n"
"/* Input Fields */\n"
"QLineEdit{\n"
"    max-height:15px;\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFFFF;\n"
"    color: #334155;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color: #0EA5E9;\n"
"    background-color: #F0F9FF;\n"
"}\n"
"\n"
"Line{\n"
"    background-color: rgba(40, 180, 244, 15);\n"
"}")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(User)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_user = QtWidgets.QWidget(parent=User)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        self.widget_user.setFont(font)
        self.widget_user.setObjectName("widget_user")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_user)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_user = QtWidgets.QLabel(parent=self.widget_user)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("background-color:transparent;")
        self.label_user.setText("")
        self.label_user.setObjectName("label_user")
        self.verticalLayout_6.addWidget(self.label_user)
        self.label_user_id = QtWidgets.QLabel(parent=self.widget_user)
        self.label_user_id.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(3)
        font.setBold(False)
        self.label_user_id.setFont(font)
        self.label_user_id.setStyleSheet("color:transparent;")
        self.label_user_id.setText("")
        self.label_user_id.setObjectName("label_user_id")
        self.verticalLayout_6.addWidget(self.label_user_id)
        self.line = QtWidgets.QFrame(parent=self.widget_user)
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(False)
        self.line.setFont(font)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_username = QtWidgets.QLabel(parent=self.widget_user)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("background-color:transparent;")
        self.label_username.setObjectName("label_username")
        self.verticalLayout.addWidget(self.label_username)
        self.input_username = QtWidgets.QLineEdit(parent=self.widget_user)
        self.input_username.setMinimumSize(QtCore.QSize(200, 0))
        self.input_username.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        self.input_username.setFont(font)
        self.input_username.setStyleSheet("")
        self.input_username.setMaxLength(12)
        self.input_username.setPlaceholderText("")
        self.input_username.setClearButtonEnabled(True)
        self.input_username.setObjectName("input_username")
        self.verticalLayout.addWidget(self.input_username)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_password = QtWidgets.QLabel(parent=self.widget_user)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        self.label_password.setFont(font)
        self.label_password.setToolTip("")
        self.label_password.setStyleSheet("background-color:transparent;")
        self.label_password.setObjectName("label_password")
        self.verticalLayout_3.addWidget(self.label_password)
        self.input_password = QtWidgets.QLineEdit(parent=self.widget_user)
        self.input_password.setMinimumSize(QtCore.QSize(200, 0))
        self.input_password.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("")
        self.input_password.setMaxLength(12)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.input_password.setPlaceholderText("")
        self.input_password.setClearButtonEnabled(True)
        self.input_password.setObjectName("input_password")
        self.verticalLayout_3.addWidget(self.input_password)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(parent=self.widget_user)
        self.button_add.setMaximumSize(QtCore.QSize(125, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.button_add.setFont(font)
        self.button_add.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_add.setStyleSheet("QPushButton{\n"
"    color:#006EFF;\n"
"}\n"
"")
        self.button_add.setIconSize(QtCore.QSize(20, 20))
        self.button_add.setCheckable(False)
        self.button_add.setAutoExclusive(False)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_cancel = QtWidgets.QPushButton(parent=self.widget_user)
        self.button_cancel.setMaximumSize(QtCore.QSize(125, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.button_cancel.setFont(font)
        self.button_cancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_cancel.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 53, 53);\n"
"}")
        self.button_cancel.setIconSize(QtCore.QSize(20, 20))
        self.button_cancel.setCheckable(False)
        self.button_cancel.setAutoExclusive(False)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_delete = QtWidgets.QPushButton(parent=self.widget_user)
        self.button_delete.setMaximumSize(QtCore.QSize(40, 33))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        self.button_delete.setFont(font)
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_delete.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button_delete.setStyleSheet("")
        self.button_delete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_delete.setIcon(icon1)
        self.button_delete.setIconSize(QtCore.QSize(20, 20))
        self.button_delete.setCheckable(False)
        self.button_delete.setAutoExclusive(False)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.widget_user)

        self.retranslateUi(User)
        QtCore.QMetaObject.connectSlotsByName(User)

    def retranslateUi(self, User):
        _translate = QtCore.QCoreApplication.translate
        self.label_username.setText(_translate("User", "İstifadəçi adı*"))
        self.label_password.setText(_translate("User", "Şifrə*"))
        self.button_add.setText(_translate("User", "Təsdiqlə"))
        self.button_cancel.setText(_translate("User", "Ləğv et"))

import resources
